#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Sweet-Ambar-Blue-Dark-v40'
ICONS='Tela-circle-nord-dark'
FONT='Noto Sans 11'
CURSOR='Bibata-Modern-Ice'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
